version: "3"

#networks:
#  my_network:
#    driver: overlay

services:
  my_website:
    image: httpd:2.4
    volumes:
      - ./www:/usr/local/apache2/htdocs/
  #    deploy:
  #      replicas: 2
  #      ressources:
  #        limites:
  #          cpus: "0.2"
  #          memory: 100M
  #    restart_policy: 
  #      condition: on-failure             
    ports:
      - "8000:80"
    logging:
      driver: "journald"
#      options:
#        gelf-address: "tcp://127.0.0.1:5000"
#        tag: "Logger-test"
#    networks:
#      - my_network
