version: '3'

services:
  proxy:
    image: traefik
    command: "--web --docker --docker.domain=docker.localhost --logLevel=DEBUG"
    networks:
      - distributed
    ports:
      - "8089:80"
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      #- ./test.txt:/tmp/test.txt

networks:
  distributed: 
    external: true
